brews:
  - tap:
      owner: juliaogris
      name: tap
      branch: master
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "Update brew formula for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/juliaogris/orderer"
    description: "orderer is a CLI for importing orders into shopify."
    license: "Apache-2.0"

    skip_upload: true

