name: ci/cd

on:
  push:
    branches: [ master ]
  pull_request:

env:
  # test store must have no orders
  SHOPIFY_STORE: ${{secrets.SHOPIFY_STORE}}
  SHOPIFY_TOKEN: ${{secrets.SHOPIFY_TOKEN}}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./bin/make ci

  release:
    runs-on: ubuntu-latest
    needs: [ ci ]
    if: github.event_name == 'push' # only run on push to master
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - run: ./bin/make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
